# Generated by Django 4.2.9 on 2026-05-06 05:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('complaint_submitted', 'Complaint Submitted'), ('status_update', 'Status Update'), ('complaint_resolved', 'Complaint Resolved'), ('complaint_escalated', 'Complaint Escalated'), ('sla_warning', 'SLA Warning'), ('assignment', 'New Assignment'), ('emergency', 'Emergency Alert'), ('system', 'System Notification')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='complaints.complaint')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
