# Generated by Django 4.2.9 on 2026-05-06 05:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('water', 'Water Supply'), ('roads', 'Roads & Infrastructure'), ('electricity', 'Electricity'), ('healthcare', 'Healthcare'), ('sanitation', 'Sanitation & Waste'), ('transport', 'Public Transport'), ('emergency', 'Emergency'), ('public_safety', 'Public Safety'), ('education', 'Education'), ('housing', 'Housing'), ('environment', 'Environment'), ('other', 'Other')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='submitted', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('sentiment', models.CharField(choices=[('angry', 'Angry'), ('frustrated', 'Frustrated'), ('urgent', 'Urgent'), ('neutral', 'Neutral'), ('satisfied', 'Satisfied')], default='neutral', max_length=20)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_category_confidence', models.FloatField(default=0.0)),
                ('is_spam', models.BooleanField(default=False)),
                ('spam_score', models.FloatField(default=0.0)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('image_verified', models.BooleanField(default=True)),
                ('image_mismatch_reason', models.TextField(blank=True)),
                ('delay_predicted', models.BooleanField(default=False)),
                ('delay_probability', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('is_voice_complaint', models.BooleanField(default=False)),
                ('language', models.CharField(default='en', max_length=10)),
            ],
            options={
                'db_table': 'complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='complaint_attachments/')),
                ('file_type', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'complaint_attachments',
            },
        ),
        migrations.CreateModel(
            name='ComplaintHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'complaint_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True)),
                ('is_satisfied', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
