# Generated by Django 4.2.9 on 2026-05-06 05:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('report_type', models.CharField(choices=[('daily', 'Daily Report'), ('weekly', 'Weekly Report'), ('monthly', 'Monthly Report'), ('custom', 'Custom Report'), ('department', 'Department Report')], max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/')),
            ],
            options={
                'db_table': 'ai_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('total_complaints', models.IntegerField(default=0)),
                ('new_complaints', models.IntegerField(default=0)),
                ('resolved_complaints', models.IntegerField(default=0)),
                ('pending_complaints', models.IntegerField(default=0)),
                ('emergency_complaints', models.IntegerField(default=0)),
                ('avg_resolution_time', models.FloatField(default=0.0)),
                ('citizen_satisfaction', models.FloatField(default=0.0)),
                ('governance_score', models.FloatField(default=0.0)),
                ('category_breakdown', models.JSONField(default=dict)),
                ('district_breakdown', models.JSONField(default=dict)),
                ('department_breakdown', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'analytics_snapshots',
                'ordering': ['-date'],
            },
        ),
    ]
